name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: $GITHUB_ACTOR
        password: ${{ secrets.CR_PAT }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.1.0
      with:
        pull: true
        platforms: linux/amd64
        push: true
        tags: ghcr.io/serverwentdown/upl:latest


# vim: set et ts=2 sw=2:
